// Generated by scripts/build-elements.mjs — do not edit by hand.
// Self-registering entry for the "scroll-stage" component.
import { defineElement, type CombatElementConstructor } from "../internal/base-element";
import * as mod from "../components/scroll-stage/index";

const exported = mod as unknown as Record<string, unknown>;
for (const value of Object.values(exported)) {
  if (
    typeof value === "function" &&
    typeof (value as { tagName?: unknown }).tagName === "string"
  ) {
    defineElement(value as CombatElementConstructor);
  }
}

export * from "../components/scroll-stage/index";
